repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        name: lint
        args: [--fix]
        files: ^libs/argus/
      - id: ruff-format
        name: format
        files: ^libs/argus/
      - id: ruff
        name: sort imports
        args: [--select, I, --fix]
        files: ^libs/argus/
